SAMP: "/mount/cifs_07793_newLEAF/Workfiles/WP4/Oak/Oak genotyping"
data: "/mount/cifs_07793_newLEAF/Workfiles/WP4/Oak/Oak genotyping/EG_FirstBatch_N182/FASTQ"
clean: "/mount/cifs_07793_newLEAF/Workfiles/WP4/Oak/Oak genotyping/data"
analyses: "/mount/cifs_07793_newLEAF/Workfiles/WP4/Oak/Oak genotyping/analyses"
samples_file: "/mount/cifs_07793_newLEAF/Workfiles/WP4/Oak/Oak genotyping/samplesfile.txt"
