SAMP: /home/projects/ku_00004/people/maxmue/popgen.kit
data: /home/projects/ku_00004/data/Jill/raw_data/delivery_20250603-1536
clean: /home/projects/ku_00004/people/maxmue/popgen.kit/data
analyses: /home/projects/ku_00004/people/maxmue/popgen.kit/analyses
samples_file: /home/projects/ku_00004/people/maxmue/popgen.kit/kaas.txt